/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nlpstemming.view;

import java.util.ArrayList;
import nlpstemming.Dictionary.ArrayDictionary;
import nlpstemming.Marks;
import nlpstemming.SentenceSlicer;
import nlpstemming.Stemmer;
import nlpstemming.tools;

/**
 *
 * @author Irfan AFif
 */
public class ViewOutput extends javax.swing.JFrame {

    /**
     * Creates new form ViewOutput
     */
    public ViewOutput() {
        initComponents();
    }
    
    public ViewOutput(String input) {
        initComponents();
        try{
            SentenceSlicer sentenceSlicer = new SentenceSlicer(input);
            ArrayList<ArrayList> output = sentenceSlicer.getListSentence();
            StringBuilder sb = new StringBuilder();
            System.out.println("output length " + output.size());
            String[] words = tools.getWordsFromFile();
            ArrayDictionary dictionary = new ArrayDictionary(words);
            Stemmer stemmer    = new Stemmer(dictionary);
            for (int i = 0; i < output.size(); i++) {
                ArrayList<String> sentenceInput = output.get(i);
                Marks marks = new Marks(sentenceInput);
                ArrayList<String> tokenizeList = marks.getSentence();
                if (i > 0){
                    sb.append("\n\nSentence ").append(i).append(":\n");
                }else{
                    sb.append("Sentence ").append(i).append(":\n");
                }
                for (int j = 0; j < tokenizeList.size(); j++) {
                    String string = tokenizeList.get(j);
                    if (j==0){
                        sb.append(string);
                    }else{
                        sb.append(" ").append(string);
                    }
                }
                sb.append("\nSTEMMING WORD : ");
                for (String string : tokenizeList) {
                    sb.append("\n").append(string).append(" => ").append(stemmer.stem(string));
                }
            }
            jTextArea1.setText(sb.toString());
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewOutput().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
